### PR TITLE
Change the yearMonth select box value format: YYYYMM -> YYYMM01

### PR DESCRIPTION
**Pull request by oHirokiKumamoto**
Follow Team spirit html change

### CODE REVIEW

**Comment by oHirokiKumamoto** [comment]
@aYosukeAkatsuka If you don't mind, Please check it out

**Comment by aYosukeAkatsuka** [comment]
@aHirokiKumamoto 
I've already checked. It looks really good to me! Go for merge!

**Comment by oHirokiKumamoto** [comment]
@aYosukeAkatsuka Thank a lot!

**Comment by oHirokiKumamoto** [comment]
[姉がギャル](http://jigokuno.com/?eid=1454)

**Pull request merged**
